### ISSUE TITLE
Unable to locate zip from actions workflow.

### ISSUE THREAD

**Issue by t3chbits** [fortify/gha-setup-scancentral-client#6]
We have the following snippet in our workflow as per your documentation:

  ```
fortify-sast:
    name: Fortify SAST Scan
    needs: build
    runs-on: self-hosted
    steps:
      - name: Fortify ScanCentral Scan
        uses: fortify/gha-setup-scancentral-client@v1.2.0
```

We are receiving an error on the run of the job: 
Unable to locate executable file: unzip. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.
